### ISSUE TITLE
입고 테스트 코드

### ISSUE THREAD

**Issue by dabbbin** [ssg-240304-java2/wms-albumshop#65]
## 어떤 기능인가요?
입고 기능을 테스트합니다. 
> 창고에 앨범이 제대로 추가되는 지 확인하는 기능입니다. 

## 작업 상세 내용

- [x] insertAlbumStorage test
- [x] updateAlbumStorage test 
- [x] isExistAlbum test

**Comment by speter6501** [comment]
버그도 해결해서 커밋올렸습니다
